// Catálogo de projetos. Um projeto pode ter várias linguagens.
const LANGS = {
  csharp:     { name: 'C#',                      icon: 'dotnet',     color: '#781B32', blurb: 'Back-end e motores de negociação em C# e .NET 8.' },
  java:       { name: 'Java',                    icon: 'openjdk',    color: '#541525', blurb: 'Back-end em Java 21 com Spring Boot.' },
  python:     { name: 'Python',                  icon: 'python',     color: '#3B0F1C', blurb: 'Ferramentas, bots e automações em Python.' },
  javascript: { name: 'JavaScript · HTML · CSS', icon: 'javascript', color: '#A52A45', blurb: 'Jogos e sites em JavaScript puro, HTML semântico e CSS sem framework e sem build.' },
};

const GH = 'https://github.com/condeDeveloper/';
const PAGES = 'https://condedeveloper.github.io/';
const game = (slug, name, icon, desc) => ({ slug, name, icon, desc, url: PAGES + slug + '/', repo: GH + slug, langs: ['javascript'], kind: 'jogo' });

const PROJECTS = [
  { slug: 'simples-nacional', name: 'Simples Nacional', icon: '🧾', desc: 'Calculadora do DAS em C# e .NET 8: os cinco anexos da LC 123/2006 com as tabelas se autovalidando na carga, alíquota efetiva com parcela a deduzir (a conta que quase toda planilha erra usando a nominal), fator R decidindo entre os anexos III e V com o cálculo de quanto falta de folha para virar, sublimite de R$ 3,6 milhões tirando ICMS e ISS do DAS, CPP fora do DAS no Anexo IV, RBT12 anualizado para início de atividade e repartição do imposto entre União, estado e município fechando ao centavo.', url: GH + 'simples-nacional#readme', repo: GH + 'simples-nacional', langs: ['csharp'], kind: 'back-end' },
  { slug: 'precificador-de-frete', name: 'Precificador de Frete', icon: '🚚', desc: 'Motor de cotação de frete em C# e .NET 8: zona tarifária deduzida das 31 faixas de CEP dos Correios (incluindo as que se intercalam entre DF e GO), peso cubado comparado ao real no total da carga, tabela por faixa de peso com excedente por quilo, ad valorem, GRIS, pedágio por fração de 100 kg, área de difícil acesso, ICMS calculado por dentro e prazo em dias úteis com os feriados móveis saindo do algoritmo de Meeus/Butcher para a Páscoa.', url: GH + 'precificador-de-frete#readme', repo: GH + 'precificador-de-frete', langs: ['csharp'], kind: 'back-end' },
  { slug: 'analisador-de-logs', name: 'Analisador de Logs', icon: '📊', desc: 'Analisador de logs em Python puro: leitores de Apache/nginx, JSON por linha, syslog e log de aplicação com detecção automática de formato e suporte a arquivo misturado, extração de pares chave=valor soltos na mensagem, linguagem de filtro própria com comparação tipada (nível comparado por gravidade, não pelo alfabeto), percentis por interpolação, série temporal com janelas vazias preenchidas, detecção de picos e relatório de terminal com barras e sparkline.', url: GH + 'analisador-de-logs#readme', repo: GH + 'analisador-de-logs', langs: ['python'], kind: 'ferramenta' },
  { slug: 'motor-de-regex', name: 'Motor de Regex', icon: '🔤', desc: 'Motor de expressões regulares do zero em Java 21: parser por descida recursiva com a precedência certa, construção de Thompson transformando a árvore em autômato e simulação por conjunto de estados — sem retrocesso, e portanto imune a ReDoS. O caso clássico (a+)+b, que trava java.util.regex, roda aqui em milissegundos contra 2000 caracteres. Classes, quantificadores com contador, alternância, âncoras e borda de palavra.', url: GH + 'motor-de-regex#readme', repo: GH + 'motor-de-regex', langs: ['java'], kind: 'biblioteca' },
  { slug: 'indice-invertido', name: 'Índice Invertido', icon: '🔎', desc: 'Motor de busca textual escrito do zero em C# e .NET 8, sem Lucene: esteira de análise com normalização, lista de parada e radicalizador de português baseado no RSLP, índice invertido com postings posicionais, trie do vocabulário para busca por prefixo, ordenação por BM25 com saturação e normalização por comprimento, busca por frase exata que atravessa as palavras de parada, sintaxe com +obrigatório, -excluído e prefixo*, trecho destacado na janela de maior concentração de termos e índice persistido em formato binário com varint e codificação por diferença.', url: GH + 'indice-invertido#readme', repo: GH + 'indice-invertido', langs: ['csharp'], kind: 'back-end' },
  { slug: 'planilha', name: 'Planilha', icon: '🧮', desc: 'Motor de planilha em Python puro, sem dependência nenhuma: lexer e parser de fórmulas escritos do zero com a precedência do Excel (inclusive o sinal unário unindo mais forte que a potência), referências A1 com cifrão e intervalos, mais de cinquenta funções em cinco famílias, erros como valor de primeira classe que se propagam e podem ser capturados com SEERRO, grafo de dependências com recálculo topológico incremental e detecção de referência circular que mostra o caminho inteiro do ciclo. Com CLI e modo interativo.', url: GH + 'planilha#readme', repo: GH + 'planilha', langs: ['python'], kind: 'biblioteca' },
  { slug: 'agendador-de-tarefas', name: 'Agendador de Tarefas', icon: '⏰', desc: 'Agendador por expressão cron em C# e .NET 8: parser de cinco ou seis campos com listas, faixas, passos, faixa que dá a volta, nomes de mês e dia, último dia do mês e enésimo dia da semana, próximo disparo calculado no fuso certo inclusive nas viradas do horário de verão, retentativa com recuo exponencial e embaralhamento, limite de tempo por execução, política de sobreposição, recolhimento de execuções órfãs e reserva atômica por UPDATE condicional em SQLite para que dois processos não rodem a mesma janela.', url: GH + 'agendador-de-tarefas#readme', repo: GH + 'agendador-de-tarefas', langs: ['csharp'], kind: 'back-end' },
  { slug: 'leitor-de-nfe', name: 'Leitor de NF-e', icon: '📄', desc: 'Leitor e conferente de NF-e 4.00 em C# e .NET 8: abre a chave de acesso de 44 dígitos com dígito verificador módulo 11, lê o XML da nota e do procNFe com XmlReader sem DTD nem resolver externo, valida CNPJ e CPF, CFOP, NCM, CST e CSOSN, e cruza tudo em regras que pegam chave divergente do corpo da nota, totais que não fecham com a soma dos itens, CFOP incompatível com as UFs e CST fora do regime do emitente. Ainda monta o resumo formatado para o DANFE.', url: GH + 'leitor-de-nfe#readme', repo: GH + 'leitor-de-nfe', langs: ['csharp'], kind: 'back-end' },
  { slug: 'folha-de-pagamento', name: 'Folha de Pagamento', icon: '💼', desc: 'Motor de folha de pagamento brasileira em C# e .NET 8: INSS progressivo faixa a faixa, IRRF retido sempre pelo menor entre as deduções legais e o desconto simplificado, tabela de incidência por rubrica, horas extras com hora noturna reduzida e reflexo no DSR, salário-família, décimo terceiro em avos e duas parcelas, férias com abono pecuniário, rescisão nos cinco motivos com projeção do aviso prévio e custo do empregador com provisões.', url: GH + 'folha-de-pagamento#readme', repo: GH + 'folha-de-pagamento', langs: ['csharp'], kind: 'back-end' },
  { slug: 'bilheteria', name: 'Bilheteria', icon: '🎟️', desc: 'Venda de ingressos em Java 21 e Spring Boot 3: reserva de lugares sob concorrência com lock pessimista e versão otimista, saga de compra com compensação, outbox para Kafka, consumidores idempotentes com retry e dead letter topic, chave de idempotência, circuit breaker no gateway de pagamento, Redis, JWT, Testcontainers, Docker Compose e observabilidade completa.', url: GH + 'bilheteria#readme', repo: GH + 'bilheteria', langs: ['java'], kind: 'back-end' },
  { slug: 'pedidos-distribuidos', name: 'Pedidos Distribuídos', icon: '🐳', desc: 'Sistema de pedidos pronto para containers: Clean Architecture e CQRS com MediatR, EF Core com migrations em PostgreSQL, RabbitMQ com padrão outbox e fila morta, worker separado, Redis, JWT, health checks, Serilog, OpenTelemetry com Jaeger, Prometheus e Grafana, Dockerfiles multi-stage, Docker Compose com oito serviços e CI que testa contra dependências reais e publica as imagens.', url: GH + 'pedidos-distribuidos#readme', repo: GH + 'pedidos-distribuidos', langs: ['csharp'], kind: 'back-end' },
  { slug: 'conciliador-bancario', name: 'Conciliador Bancário', icon: '🔗', desc: 'Conciliação bancária em C# e .NET 8: lê OFX (SGML e XML) e CNAB 240 com validação de trailers, CSV do sistema interno, e casa os dois lados numa cascata de regras com agrupamento e similaridade de descrição. Pendências, divergências e relatório.', url: GH + 'conciliador-bancario#readme', repo: GH + 'conciliador-bancario', langs: ['csharp'], kind: 'back-end' },
  { slug: 'cofre-kv', name: 'Cofre KV', icon: '🗄️', desc: 'Banco chave-valor em memória compatível com o protocolo do Redis: RESP2 com parser incremental, servidor TCP com Pipelines e laço único de execução, TTL, despejo LRU, listas e hashes. O redis-cli conecta nele.', url: GH + 'cofre-kv#readme', repo: GH + 'cofre-kv', langs: ['csharp'], kind: 'back-end' },
  { slug: 'motor-de-credito', name: 'Motor de Crédito', icon: '📊', desc: 'Motor de decisão de crédito em C# e .NET 8: scorecard declarativo, faixas de risco A a E, política com cortes e contraproposta, planos Price e SAC, IOF e CET por taxa interna de retorno.', url: GH + 'motor-de-credito#readme', repo: GH + 'motor-de-credito', langs: ['csharp'], kind: 'back-end' },
  { slug: 'boleto-bancario', name: 'Boleto Bancário', icon: '🧾', desc: 'Boletos FEBRABAN em C# e .NET 8: código de barras, linha digitável, módulo 10 e 11, fator de vencimento com a virada de 2025, campo livre de cinco bancos e SVG Interleaved 2 of 5.', url: GH + 'boleto-bancario#readme', repo: GH + 'boleto-bancario', langs: ['csharp'], kind: 'biblioteca' },
  { slug: 'chatbot-bobo', name: 'Bobo, o chatbot idiota', icon: '🤪', desc: 'Chatbot de terminal em Python puro: habilidades por prioridade, memória de conversa, contas seguras com ast, hora e data, piadas e reflexões estilo ELIZA em português. Sem dependências.', url: GH + 'chatbot-bobo#readme', repo: GH + 'chatbot-bobo', langs: ['python'], kind: 'bot' },
  { slug: 'antifraude', name: 'Antifraude', icon: '🛡️', desc: 'Motor de regras antifraude em C# e .NET 8: linguagem própria com lexer, parser e avaliador, janelas deslizantes de velocidade, decisão Aprovar/Revisar/Negar com explicação e simulação em lote.', url: GH + 'antifraude#readme', repo: GH + 'antifraude', langs: ['csharp'], kind: 'back-end' },
  { slug: 'simulador-pix', name: 'Simulador Pix', icon: '💸', desc: 'PSP recebedor Pix em C# e .NET 8: BR Code EMV com CRC16, cobranças com QR dinâmico, pagamentos, devoluções e webhooks HMAC com reentrega. EF Core e SQLite.', url: GH + 'simulador-pix#readme', repo: GH + 'simulador-pix', langs: ['csharp'], kind: 'back-end' },
  { slug: 'livro-de-ofertas', name: 'Livro de Ofertas', icon: '📈', desc: 'Motor de casamento de ofertas em C# e .NET 8: prioridade preço-tempo, GTC/IOC/FOK, auto-negociação, candles, event sourcing, API e SignalR.', url: GH + 'livro-de-ofertas#readme', repo: GH + 'livro-de-ofertas', langs: ['csharp'], kind: 'back-end' },
  { slug: 'tesouraria', name: 'Tesouraria', icon: '🏦', desc: 'Sistema financeiro em Java 21 e Spring Boot: ledger de partidas dobradas, câmbio pronto, NDF, opções com Garman-Kohlhagen e risco.', url: GH + 'tesouraria#readme', repo: GH + 'tesouraria', langs: ['java'], kind: 'back-end' },
  { slug: 'CountSite', name: 'CondeClub · site', icon: '🍷', desc: 'Landing page do CondeClub e do Manual Definitivo do Dev.', url: 'https://condecount.pages.dev/', repo: GH + 'CountSite', langs: ['javascript'], kind: 'site' },
  { slug: 'jogos', name: 'Hub de jogos', icon: '🎮', desc: 'Página que reúne todos os jogos, com busca.', url: PAGES + 'jogos/', repo: GH + 'jogos', langs: ['javascript'], kind: 'site' },
  game('tetris', 'Tetris', '🧱', '7-bag, hold, ghost piece, wall kicks, temas e ranking.'),
  game('breakout', 'Breakout', '🧨', 'Cinco níveis, tijolos reforçados, power-ups e partículas.'),
  game('space-invaders', 'Space Invaders', '👾', 'Pixel art, barreiras destrutíveis, nave misteriosa e ondas infinitas.'),
  game('asteroids', 'Asteroids', '☄️', 'Gráficos vetoriais, inércia, hiperespaço e asteroides que se dividem.'),
  game('pong', 'Pong', '🏓', 'IA com três dificuldades e modo dois jogadores.'),
  game('sudoku', 'Sudoku', '🧩', 'Gerador de puzzles de solução única, anotações e dicas.'),
  game('campo-minado', 'Campo Minado', '💣', 'Primeiro clique seguro, chord e melhores tempos.'),
  game('termo', 'Termo', '🟩', 'Palavra do dia, estatísticas e compartilhar.'),
  game('2048', '2048', '🔢', 'Desfazer, partida salva e animações.'),
  game('snake', 'Snake', '🐍', 'Comida dourada, velocidade progressiva, swipe e d-pad.'),
  game('flappy-bird', 'Flappy Bird', '🐦', 'Medalhas e ciclo dia/noite.'),
  game('dino-runner', 'Dino Runner', '🦖', 'Corredor infinito com pássaros e dia/noite.'),
  game('jogo-da-velha', 'Jogo da Velha', '❌', 'IA minimax imbatível e modo dois jogadores.'),
  game('genius', 'Genius', '🎵', 'Sequência de cores e sons com tons afinados.'),
  game('jogo-da-memoria', 'Jogo da Memória', '🧠', 'Cartas 3D, três temas e recorde por nível.'),
  game('acerte-a-toupeira', 'Acerte a Toupeira', '🐹', 'Trinta segundos, combo, dourada e bombas.'),
];
